reload:
get_schedule:
  target:
    entity:
      domain: schedule
advance_schedule:
  target:
    entity:
      domain: schedule
alter_schedule:
  target:
    entity:
      domain: schedule
  fields:
    state:
      required: true
      selector:
        text:
boost_schedule:
  target:
    entity:
      domain: schedule
  fields:
    duration:
      example: "00:01:00 or 60"
      required: true
      selector:
        duration:
    state:
      required: true
      selector:
        text:
debug_schedule:
  target:
    entity:
      domain: schedule
dump_schedule:
  target:
    entity:
      domain: schedule
refresh_schedule:
  target:
    entity:
      domain: schedule
  fields:
    offset:
      required: true
      default: 0
      selector:
        number:
          min: -21600
          max: 21600
          mode: box
