reload:
get_schedule:
  target:
    entity:
      domain: dynamic_schedule
advance_schedule:
  target:
    entity:
      domain: dynamic_schedule
alter_schedule:
  target:
    entity:
      domain: dynamic_schedule
  fields:
    state:
      required: true
      selector:
        text:
boost_schedule:
  target:
    entity:
      domain: dynamic_schedule
  fields:
    duration:
      example: "00:01:00 or 60"
      required: true
      selector:
        duration:
    state:
      required: true
      selector:
        text:
debug_schedule:
  target:
    entity:
      domain: dynamic_schedule
dump_schedule:
  target:
    entity:
      domain: dynamic_schedule
refresh_schedule:
  target:
    entity:
      domain: dynamic_schedule
  fields:
    offset:
      required: true
      default:
        days: 0
        hours: 0
        minutes: 0
        seconds: 0
      selector:
        duration:
          allow_negative: true
